#!/bin/sh
set -e
package_name=big-lxqt-tweaks
case "$1" in
  remove)
    dpkg-divert --package "$package_name" --rename --remove "/usr/share/lxqt/themes/kde-plasma/lxqt-panel.qss"
    dpkg-divert --package "$package_name" --rename --remove "/usr/share/desktop-directories/lxde-settings.directory"
    dpkg-divert --package "$package_name" --rename --remove "/usr/share/desktop-directories/lxde-utility.directory"
    dpkg-divert --package "$package_name" --rename --remove "/usr/share/desktop-directories/lxqt-settings.directory"
    dpkg-divert --package "$package_name" --rename --remove "/usr/share/applications/lxqt-leave.desktop"
    dpkg-divert --package "$package_name" --rename --remove "/etc/xdg/menus/lxqt-applications.menu"
    ;;
  purge)
    dpkg-divert --package "$package_name" --rename --remove "/usr/share/lxqt/themes/kde-plasma/lxqt-panel.qss"
    dpkg-divert --package "$package_name" --rename --remove "/usr/share/desktop-directories/lxde-settings.directory"
    dpkg-divert --package "$package_name" --rename --remove "/usr/share/desktop-directories/lxde-utility.directory"
    dpkg-divert --package "$package_name" --rename --remove "/usr/share/desktop-directories/lxqt-settings.directory"
    dpkg-divert --package "$package_name" --rename --remove "/usr/share/applications/lxqt-leave.desktop"
    dpkg-divert --package "$package_name" --rename --remove "/etc/xdg/menus/lxqt-applications.menu"
;;
esac
exit 0
